(function() {var implementors = {};
implementors["edit_client"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"edit_client/random/struct.RandomCursorContext.html\" title=\"struct edit_client::random::RandomCursorContext\">RandomCursorContext</a>",synthetic:false,types:["edit_client::random::RandomCursorContext"]},];
implementors["edit_server"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"edit_server/db/schema/logs/columns/struct.rowid.html\" title=\"struct edit_server::db::schema::logs::columns::rowid\">rowid</a>",synthetic:false,types:["edit_server::db::schema::logs::columns::rowid"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"edit_server/db/schema/logs/columns/struct.source.html\" title=\"struct edit_server::db::schema::logs::columns::source\">source</a>",synthetic:false,types:["edit_server::db::schema::logs::columns::source"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"edit_server/db/schema/logs/columns/struct.body.html\" title=\"struct edit_server::db::schema::logs::columns::body\">body</a>",synthetic:false,types:["edit_server::db::schema::logs::columns::body"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"edit_server/db/schema/posts/columns/struct.id.html\" title=\"struct edit_server::db::schema::posts::columns::id\">id</a>",synthetic:false,types:["edit_server::db::schema::posts::columns::id"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"edit_server/db/schema/posts/columns/struct.body.html\" title=\"struct edit_server::db::schema::posts::columns::body\">body</a>",synthetic:false,types:["edit_server::db::schema::posts::columns::body"]},];
implementors["oatie"] = [{text:"impl&lt;S:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> + <a class=\"trait\" href=\"oatie/doc/trait.Schema.html\" title=\"trait oatie::doc::Schema\">Schema</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"oatie/writer/struct.DelWriter.html\" title=\"struct oatie::writer::DelWriter\">DelWriter</a>&lt;S&gt;",synthetic:false,types:["oatie::writer::DelWriter"]},{text:"impl&lt;S:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> + <a class=\"trait\" href=\"oatie/doc/trait.Schema.html\" title=\"trait oatie::doc::Schema\">Schema</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"oatie/writer/struct.AddWriter.html\" title=\"struct oatie::writer::AddWriter\">AddWriter</a>&lt;S&gt;",synthetic:false,types:["oatie::writer::AddWriter"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"oatie/writer/struct.CurWriter.html\" title=\"struct oatie::writer::CurWriter\">CurWriter</a>",synthetic:false,types:["oatie::writer::CurWriter"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"oatie/rtf/struct.StyleSet.html\" title=\"struct oatie::rtf::StyleSet\">StyleSet</a>",synthetic:false,types:["oatie::rtf::StyleSet"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
