[package]
authors = ["Tim Ryan <id@timryan.org>"]
name = "mercutio"
version = "0.1.0"
[dependencies]
bodyparser = "0.7"
bus = "1.3.2"
crossbeam-channel = "0.1.2"
env_logger = "0.4.3"
failure = "0.1.1"
iron = "0.5"
maplit = "1.0.0"
mount = "0.3"
rand = "0.3.18"
rocket = "0.3.3"
rocket_codegen = "0.3.3"
rocket_contrib = "0.3.3"
router = "0.5"
serde = "1.0.21"
serde_derive = "1.0.21"
serde_json = "1.0.6"
staticfile = "0.4"
take_mut = "0.2.0"
ws = "0.7.3"

[dependencies.oatie]
path = "../oatie"
