[package]
name = "mote"
version = "0.1.0"
authors = ["Tim Ryan <tim@3drobotics.com>"]

[dependencies]
bodyparser = "0.7"
iron = "0.5"
mount = "0.3"
router = "0.5"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
staticfile = "0.4"

[dependencies.oatie]
path = "../oatie"
