[package]
name = "mote"
version = "0.1.0"
authors = ["Tim Ryan <tim@3drobotics.com>"]

[dependencies]
bodyparser = "0.4"
iron = "0.4"
mount = "0.2"
router = "0.4"
serde = "0.8"
serde_derive = "0.8"
serde_json = "0.8"
staticfile = "0.3"

[dependencies.oatie]
path = "../oatie"
