[package]
authors = ["Tim Ryan <id@timryan.org>"]
name = "mercutio-web"
version = "0.1.0"
[dependencies]
serde = "1.0.23"
serde_derive = "1.0.23"
serde_json = "1.0.7"

[dependencies.oatie]
path = "../../oatie"

[lib]
# crate-type = ["cdylib"]
name = "mercutio_web"
