[package]

name = "oatie"
version = "0.2.0"
authors = ["Tim Cameron Ryan <id@timryan.org>"]

[dependencies]
rand = "0.3.7"
log = "0.3.1"
env_logger = "0.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
term-painter = "0.2.2"

[lib]
name = "oatie"
