var N = null;var sourcesIndex = {};
sourcesIndex['build_tools'] = {"name":"","dirs":[{"name":"cargo_watch","dirs":[],"files":["mod.rs"]},{"name":"mdbook_bin","dirs":[],"files":["mod.rs","serve.rs","svgbob.rs","watch.rs"]}],"files":["main.rs"]};
sourcesIndex['edit_client'] = {"name":"","dirs":[{"name":"client","dirs":[{"name":"actions","dirs":[],"files":["caret.rs","identify.rs","modify.rs","styles.rs"]}],"files":["actions.rs","clientdoc.rs"]},{"name":"walkers","dirs":[],"files":["caretstepper.rs"]}],"files":["client.rs","lib.rs","log.rs","monkey.rs","proxy.rs","random.rs","walkers.rs"]};
sourcesIndex['edit_client_proxy'] = {"name":"","dirs":[],"files":["edit-client-proxy.rs"]};
sourcesIndex['edit_common'] = {"name":"","dirs":[{"name":"markdown","dirs":[],"files":["de.rs","mod.rs","ser.rs"]}],"files":["commands.rs","lib.rs","simple_ws.rs"]};
sourcesIndex['edit_replay'] = {"name":"","dirs":[],"files":["edit-replay.rs"]};
sourcesIndex['edit_server'] = {"name":"","dirs":[{"name":"db","dirs":[],"files":["queries.rs","schema.rs","types.rs"]},{"name":"graphql","dirs":[],"files":["client.rs","server.rs"]}],"files":["carets.rs","db.rs","graphql.rs","lib.rs","log.rs","state.rs","sync.rs"]};
sourcesIndex['edit_server_logs'] = {"name":"","dirs":[],"files":["edit-server-logs.rs"]};
sourcesIndex['oatie'] = {"name":"","dirs":[{"name":"core","dirs":[],"files":["apply.rs","compose.rs","doc.rs","place.rs","schema.rs","style.rs","transform.rs"]},{"name":"stepper","dirs":[],"files":["docmutator.rs","docstepper.rs"]},{"name":"string","dirs":[],"files":["charcursor.rs","docstring.rs"]}],"files":["core.rs","lib.rs","macros.rs","normalize.rs","parse.rs","stepper.rs","string.rs","transform_test.rs","validate.rs","wasm.rs","writer.rs"]};
sourcesIndex['oatie_transform'] = {"name":"","dirs":[],"files":["oatie-transform.rs"]};
